[2025-07-19T18:05:52.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze manual__2025-07-19T18:05:48.197266+00:00 [queued]>
[2025-07-19T18:05:53.006+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.stream_to_bronze manual__2025-07-19T18:05:48.197266+00:00 [queued]>
[2025-07-19T18:05:53.007+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-19T18:05:53.013+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): stream_to_bronze> on 2025-07-19 18:05:48.197266+00:00
[2025-07-19T18:05:53.015+0000] {standard_task_runner.py:57} INFO - Started process 329 to run task
[2025-07-19T18:05:53.017+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'stream_to_bronze', 'manual__2025-07-19T18:05:48.197266+00:00', '--job-id', '930', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmp2to3z24b']
[2025-07-19T18:05:53.018+0000] {standard_task_runner.py:85} INFO - Job 930: Subtask stream_to_bronze
[2025-07-19T18:05:53.040+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.stream_to_bronze manual__2025-07-19T18:05:48.197266+00:00 [running]> on host e3f5d8fc4eef
[2025-07-19T18:05:53.074+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your@email.com' AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='stream_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T18:05:48.197266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T18:05:48.197266+00:00'
[2025-07-19T18:05:53.075+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-19T18:05:53.075+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "docker exec -e AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T18:05:48.197266+00:00' spark-iceberg spark-submit /home/iceberg/spark/stream_to_bronze.py"]
[2025-07-19T18:05:53.079+0000] {subprocess.py:86} INFO - Output:
[2025-07-19T18:05:54.403+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkContext: Running Spark version 3.5.6
[2025-07-19T18:05:54.404+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:05:54.404+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkContext: Java version 17.0.15
[2025-07-19T18:05:54.417+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceUtils: ==============================================================
[2025-07-19T18:05:54.417+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-19T18:05:54.417+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceUtils: ==============================================================
[2025-07-19T18:05:54.417+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkContext: Submitted application: StreamToBronze
[2025-07-19T18:05:54.425+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-19T18:05:54.429+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceProfile: Limiting resource is cpu
[2025-07-19T18:05:54.429+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-19T18:05:54.451+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SecurityManager: Changing view acls to: root,spark
[2025-07-19T18:05:54.452+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SecurityManager: Changing modify acls to: root,spark
[2025-07-19T18:05:54.452+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SecurityManager: Changing view acls groups to:
[2025-07-19T18:05:54.452+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SecurityManager: Changing modify acls groups to:
[2025-07-19T18:05:54.452+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root, spark; groups with view permissions: EMPTY; users with modify permissions: root, spark; groups with modify permissions: EMPTY
[2025-07-19T18:05:54.480+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-19T18:05:54.600+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Utils: Successfully started service 'sparkDriver' on port 38261.
[2025-07-19T18:05:54.614+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkEnv: Registering MapOutputTracker
[2025-07-19T18:05:54.635+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-19T18:05:54.648+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-19T18:05:54.648+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-19T18:05:54.651+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-19T18:05:54.661+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-fa013a0c-cd17-466c-9fbf-e9a62fb13c50
[2025-07-19T18:05:54.666+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-19T18:05:54.673+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-19T18:05:54.734+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-19T18:05:54.777+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-07-19T18:05:54.781+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-07-19T18:05:54.830+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Executor: Starting executor ID driver on host 8b44f3d35cfa
[2025-07-19T18:05:54.830+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Executor: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-07-19T18:05:54.830+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Executor: Java version 17.0.15
[2025-07-19T18:05:54.833+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-19T18:05:54.834+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@3fe522f9 for default.
[2025-07-19T18:05:54.844+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40485.
[2025-07-19T18:05:54.844+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO NettyBlockTransferService: Server created on 8b44f3d35cfa:40485
[2025-07-19T18:05:54.844+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-19T18:05:54.852+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8b44f3d35cfa, 40485, None)
[2025-07-19T18:05:54.853+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManagerMasterEndpoint: Registering block manager 8b44f3d35cfa:40485 with 434.4 MiB RAM, BlockManagerId(driver, 8b44f3d35cfa, 40485, None)
[2025-07-19T18:05:54.857+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8b44f3d35cfa, 40485, None)
[2025-07-19T18:05:54.857+0000] {subprocess.py:93} INFO - 25/07/19 18:05:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8b44f3d35cfa, 40485, None)
[2025-07-19T18:05:55.074+0000] {subprocess.py:93} INFO - 25/07/19 18:05:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-07-19T18:05:55.078+0000] {subprocess.py:93} INFO - 25/07/19 18:05:55 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2025-07-19T18:05:56.225+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-07-19T18:05:56.231+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-07-19T18:05:56.232+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-07-19T18:05:56.835+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO BaseMetastoreCatalog: Table loaded by catalog: my_catalog.bronze.Reservations_raw
[2025-07-19T18:05:56.850+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
[2025-07-19T18:05:56.884+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO ResolveWriteToStream: Checkpoint root /tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00 resolved to file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00.
[2025-07-19T18:05:56.884+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 WARN ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.
[2025-07-19T18:05:56.915+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO CheckpointFileManager: Writing atomically to file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00/metadata using temp file file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00/.metadata.297dda88-c7cb-4157-bdd4-28d7dc4501eb.tmp
[2025-07-19T18:05:56.952+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO CheckpointFileManager: Renamed temp file file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00/.metadata.297dda88-c7cb-4157-bdd4-28d7dc4501eb.tmp to file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00/metadata
[2025-07-19T18:05:56.970+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO MicroBatchExecution: Starting [id = bb1c2972-089c-43a2-bf16-c3ad5fda7908, runId = 64a3e4f6-9b62-48dc-963a-5a923310d6a8]. Use file:/tmp/checkpoints/reservations/manual__2025-07-19T18:05:48.197266+00:00 to store the query checkpoint.
[2025-07-19T18:05:56.979+0000] {subprocess.py:93} INFO - 25/07/19 18:05:56 INFO MicroBatchExecution: Reading table [org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@4d647f9c] from DataSourceV2 named 'kafka' [org.apache.spark.sql.kafka010.KafkaSourceProvider@559cf547]
[2025-07-19T18:05:57.005+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO OffsetSeqLog: BatchIds found from listing:
[2025-07-19T18:05:57.006+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO OffsetSeqLog: BatchIds found from listing:
[2025-07-19T18:05:57.008+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MicroBatchExecution: Starting new streaming query.
[2025-07-19T18:05:57.009+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MicroBatchExecution: Stream started from {}
[2025-07-19T18:05:57.160+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-19T18:05:57.160+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 100, in <module>
[2025-07-19T18:05:57.160+0000] {subprocess.py:93} INFO -     read_kafka(
[2025-07-19T18:05:57.161+0000] {subprocess.py:93} INFO -   File "/home/iceberg/spark/stream_to_bronze.py", line 77, in read_kafka
[2025-07-19T18:05:57.161+0000] {subprocess.py:93} INFO -     df = df.withWatermark("checkin_timestamp", "48 hours")
[2025-07-19T18:05:57.161+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-19T18:05:57.161+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 1149, in withWatermark
[2025-07-19T18:05:57.162+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-07-19T18:05:57.162+0000] {subprocess.py:93} INFO -   File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-07-19T18:05:57.166+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [EVENT_TIME_IS_NOT_ON_TIMESTAMP_TYPE] The event time `checkin_timestamp` has the invalid type "DOUBLE", but expected "TIMESTAMP".;
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO - EventTimeWatermark checkin_timestamp#103: double, 48 hours
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO - +- Project [checkin_id#83, customer_name#84, phone_number#85, branch_id#86, table_id#87, is_prebooked#88, checkin_date#89, checkin_time#90, guests_count#91, shift_manager#92, ((cast(cast(checkin_date#89 as string) as double) + cast(  as double)) + cast(checkin_time#90 as double)) AS checkin_timestamp#103]
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO -    +- Project [data#81.checkin_id AS checkin_id#83, data#81.customer_name AS customer_name#84, data#81.phone_number AS phone_number#85, data#81.branch_id AS branch_id#86, data#81.table_id AS table_id#87, data#81.is_prebooked AS is_prebooked#88, data#81.checkin_date AS checkin_date#89, data#81.checkin_time AS checkin_time#90, data#81.guests_count AS guests_count#91, data#81.shift_manager AS shift_manager#92]
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO -       +- Project [from_json(StructField(checkin_id,IntegerType,true), StructField(customer_name,StringType,true), StructField(phone_number,StringType,true), StructField(branch_id,IntegerType,true), StructField(table_id,IntegerType,true), StructField(is_prebooked,BooleanType,true), StructField(checkin_date,DateType,true), StructField(checkin_time,StringType,true), StructField(guests_count,IntegerType,true), StructField(shift_manager,StringType,true), json#79, Some(Etc/UTC)) AS data#81]
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO -          +- Project [cast(value#66 as string) AS json#79]
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO -             +- StreamingRelationV2 org.apache.spark.sql.kafka010.KafkaSourceProvider@53cf9610, kafka, org.apache.spark.sql.kafka010.KafkaSourceProvider$KafkaTable@3f53834f, [startingOffsets=earliest, kafka.bootstrap.servers=kafka:9092, subscribe=checkins], [key#65, value#66, topic#67, partition#68, offset#69L, timestamp#70, timestampType#71], StreamingRelation DataSource(org.apache.spark.sql.SparkSession@75fad0c4,kafka,List(),None,List(),None,Map(kafka.bootstrap.servers -> kafka:9092, subscribe -> checkins, startingOffsets -> earliest),None), kafka, [key#58, value#59, topic#60, partition#61, offset#62L, timestamp#63, timestampType#64]
[2025-07-19T18:05:57.167+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO AdminClientConfig: AdminClientConfig values:
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	auto.include.jmx.reporter = true
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	bootstrap.servers = [kafka:9092]
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	client.dns.lookup = use_all_dns_ips
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	client.id =
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	connections.max.idle.ms = 300000
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	default.api.timeout.ms = 60000
[2025-07-19T18:05:57.168+0000] {subprocess.py:93} INFO - 	metadata.max.age.ms = 300000
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	metric.reporters = []
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	metrics.num.samples = 2
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	metrics.recording.level = INFO
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	metrics.sample.window.ms = 30000
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	receive.buffer.bytes = 65536
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	reconnect.backoff.max.ms = 1000
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	reconnect.backoff.ms = 50
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	request.timeout.ms = 30000
[2025-07-19T18:05:57.169+0000] {subprocess.py:93} INFO - 	retries = 2147483647
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	retry.backoff.ms = 100
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.client.callback.handler.class = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.jaas.config = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.kerberos.min.time.before.relogin = 60000
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.kerberos.service.name = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.kerberos.ticket.renew.jitter = 0.05
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.kerberos.ticket.renew.window.factor = 0.8
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.callback.handler.class = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.class = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.connect.timeout.ms = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.read.timeout.ms = null
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.buffer.seconds = 300
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.min.period.seconds = 60
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.window.factor = 0.8
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.refresh.window.jitter = 0.05
[2025-07-19T18:05:57.170+0000] {subprocess.py:93} INFO - 	sasl.login.retry.backoff.max.ms = 10000
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.login.retry.backoff.ms = 100
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.mechanism = GSSAPI
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.clock.skew.seconds = 30
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.expected.audience = null
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.expected.issuer = null
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.jwks.endpoint.url = null
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.scope.claim.name = scope
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.sub.claim.name = sub
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	sasl.oauthbearer.token.endpoint.url = null
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	security.protocol = PLAINTEXT
[2025-07-19T18:05:57.171+0000] {subprocess.py:93} INFO - 	security.providers = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	send.buffer.bytes = 131072
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	socket.connection.setup.timeout.max.ms = 30000
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	socket.connection.setup.timeout.ms = 10000
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.cipher.suites = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.endpoint.identification.algorithm = https
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.engine.factory.class = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.key.password = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keymanager.algorithm = SunX509
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keystore.certificate.chain = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keystore.key = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keystore.location = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keystore.password = null
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.keystore.type = JKS
[2025-07-19T18:05:57.172+0000] {subprocess.py:93} INFO - 	ssl.protocol = TLSv1.3
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.provider = null
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.secure.random.implementation = null
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.trustmanager.algorithm = PKIX
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.truststore.certificates = null
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.truststore.location = null
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.truststore.password = null
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 	ssl.truststore.type = JKS
[2025-07-19T18:05:57.173+0000] {subprocess.py:93} INFO - 
[2025-07-19T18:05:57.196+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-19T18:05:57.196+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-19T18:05:57.201+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO SparkUI: Stopped Spark web UI at http://8b44f3d35cfa:4041
[2025-07-19T18:05:57.212+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-19T18:05:57.216+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO AdminClientConfig: These configurations '[key.deserializer, value.deserializer, enable.auto.commit, max.poll.records, auto.offset.reset]' were supplied but are not used yet.
[2025-07-19T18:05:57.217+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO AppInfoParser: Kafka version: 3.5.1
[2025-07-19T18:05:57.217+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO AppInfoParser: Kafka commitId: 2c6fb6c54472e90a
[2025-07-19T18:05:57.217+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO AppInfoParser: Kafka startTimeMs: 1752948357215
[2025-07-19T18:05:57.226+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MemoryStore: MemoryStore cleared
[2025-07-19T18:05:57.227+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO BlockManager: BlockManager stopped
[2025-07-19T18:05:57.229+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-19T18:05:57.230+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-19T18:05:57.248+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO SparkContext: Successfully stopped SparkContext
[2025-07-19T18:05:57.248+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO ShutdownHookManager: Shutdown hook called
[2025-07-19T18:05:57.248+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-bd623f59-a0a4-4422-82a0-eea2d91a137f
[2025-07-19T18:05:57.250+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-c54be6a7-9404-431b-85fd-85879b50dfad
[2025-07-19T18:05:57.251+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-c54be6a7-9404-431b-85fd-85879b50dfad/pyspark-3d3a0fb6-2438-4570-aa3c-45fbb3b4ebad
[2025-07-19T18:05:57.254+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...
[2025-07-19T18:05:57.254+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.
[2025-07-19T18:05:57.254+0000] {subprocess.py:93} INFO - 25/07/19 18:05:57 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.
[2025-07-19T18:05:57.285+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-19T18:05:57.292+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-19T18:05:57.294+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=stream_to_bronze, execution_date=20250719T180548, start_date=20250719T180553, end_date=20250719T180557
[2025-07-19T18:05:57.305+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-19T18:05:57.305+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:05:57.305+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:05:57.308+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-19T18:05:57.308+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-19T18:05:57.308+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['your@email.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-19T18:05:57.315+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 930 for task stream_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 329)
[2025-07-19T18:05:57.349+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-19T18:05:57.374+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
