[2025-07-18T14:57:57.102+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:57:55.672674+00:00 [queued]>
[2025-07-18T14:57:57.115+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:57:55.672674+00:00 [queued]>
[2025-07-18T14:57:57.115+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-18T14:57:57.125+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-07-18 14:57:55.672674+00:00
[2025-07-18T14:57:57.129+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2025-07-18T14:57:57.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'send_to_kafka', 'manual__2025-07-18T14:57:55.672674+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmpv_fwvv1p']
[2025-07-18T14:57:57.133+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask send_to_kafka
[2025-07-18T14:57:57.162+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.send_to_kafka manual__2025-07-18T14:57:55.672674+00:00 [running]> on host 340b84e33f7d
[2025-07-18T14:57:57.207+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T14:57:55.672674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-18T14:57:55.672674+00:00'
[2025-07-18T14:57:57.208+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-18T14:57:57.209+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/streaming/producer.py']
[2025-07-18T14:57:57.215+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:57:59.571+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:57:59.572+0000] {subprocess.py:93} INFO -   File "/opt/streaming/producer.py", line 7, in <module>
[2025-07-18T14:57:59.572+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-07-18T14:57:59.573+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 481, in __init__
[2025-07-18T14:57:59.573+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-07-18T14:57:59.573+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
[2025-07-18T14:57:59.573+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-07-18T14:57:59.574+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
[2025-07-18T14:57:59.574+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-07-18T14:57:59.574+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-07-18T14:57:59.605+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:57:59.612+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:57:59.614+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=send_to_kafka, execution_date=20250718T145755, start_date=20250718T145757, end_date=20250718T145759
[2025-07-18T14:57:59.621+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 293)
[2025-07-18T14:57:59.631+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-18T14:57:59.654+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
