[2025-07-18T14:48:02.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:46:00+00:00 [queued]>
[2025-07-18T14:48:02.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:46:00+00:00 [queued]>
[2025-07-18T14:48:02.260+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-18T14:48:02.269+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-07-18 14:46:00+00:00
[2025-07-18T14:48:02.273+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2025-07-18T14:48:02.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'send_to_kafka', 'scheduled__2025-07-18T14:46:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmp9tx3ru98']
[2025-07-18T14:48:02.280+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask send_to_kafka
[2025-07-18T14:48:02.325+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:46:00+00:00 [running]> on host 1bb915623a17
[2025-07-18T14:48:02.404+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T14:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T14:46:00+00:00'
[2025-07-18T14:48:02.406+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-18T14:48:02.407+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/streaming/producer.py']
[2025-07-18T14:48:02.415+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:48:02.479+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:48:02.480+0000] {subprocess.py:93} INFO -   File "/opt/streaming/producer.py", line 1, in <module>
[2025-07-18T14:48:02.480+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-07-18T14:48:02.480+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-07-18T14:48:02.481+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:48:02.488+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:48:02.490+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=send_to_kafka, execution_date=20250718T144600, start_date=20250718T144802, end_date=20250718T144802
[2025-07-18T14:48:02.496+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 209)
[2025-07-18T14:48:02.540+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-18T14:48:02.566+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
