[2025-07-18T14:54:02.053+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:52:00+00:00 [queued]>
[2025-07-18T14:54:02.057+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:52:00+00:00 [queued]>
[2025-07-18T14:54:02.058+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-18T14:54:02.063+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-07-18 14:52:00+00:00
[2025-07-18T14:54:02.065+0000] {standard_task_runner.py:57} INFO - Started process 234 to run task
[2025-07-18T14:54:02.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restaurant_pipeline', 'send_to_kafka', 'scheduled__2025-07-18T14:52:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_pipeline.py', '--cfg-path', '/tmp/tmp7g2duaj6']
[2025-07-18T14:54:02.069+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask send_to_kafka
[2025-07-18T14:54:02.092+0000] {task_command.py:416} INFO - Running <TaskInstance: restaurant_pipeline.send_to_kafka scheduled__2025-07-18T14:52:00+00:00 [running]> on host 340b84e33f7d
[2025-07-18T14:54:02.134+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='moran' AIRFLOW_CTX_DAG_ID='restaurant_pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T14:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T14:52:00+00:00'
[2025-07-18T14:54:02.136+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-18T14:54:02.137+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/streaming/producer.py']
[2025-07-18T14:54:02.146+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T14:54:04.473+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -   File "/opt/streaming/producer.py", line 7, in <module>
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 481, in __init__
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 262, in __init__
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-07-18T14:54:04.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/kafka/client_async.py", line 1074, in check_version
[2025-07-18T14:54:04.482+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-07-18T14:54:04.482+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-07-18T14:54:04.506+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T14:54:04.515+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T14:54:04.518+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restaurant_pipeline, task_id=send_to_kafka, execution_date=20250718T145200, start_date=20250718T145402, end_date=20250718T145404
[2025-07-18T14:54:04.526+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 234)
[2025-07-18T14:54:04.554+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-18T14:54:04.589+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
